command_timeout = 5000

[directory]
read_only = " ï ½"

[character]
success_symbol = "[â–¶ï¸](bold green)"
error_symbol = "[âœ˜](bold red)"

# These symbols will only show when battery levels are 20% or less
[battery]
disabled = true
charging_symbol = "ó±‹ "
discharging_symbol = "ï‰ƒ "

# Clear visibility for exit codes
[status]
style = "red"
symbol = ""
format = '[\[$symbol$status\]]($style) '
disabled = false

[gcloud]
disabled = true
format = 'on [$symbol$project]($style) '

[aws]
disabled = true
format = 'on [$symbol$profile]($style) '
style = 'blue'

[azure]
disabled = true
format = 'on [$symbol($subscription)]($style) '
symbol = 'ï´ƒ '
style = 'blue'

[git_branch]
symbol = "ï˜ "

[git_status]
stashed = "[*${count}](blue) "
modified = "[!${count}](yellow) "
staged = "[+${count}](green) "
untracked = "[?${count}](orange) "
deleted = "[-${count}](red) "
ahead = 'â‡¡${count} '
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count} '
behind = 'â‡£${count} '
format = '([$stashed$modified$staged$untracked$ahead_behind]($style))'

[hg_branch]
symbol = "ï˜ "

# More Nerd Font Symbols

[buf]
symbol = "ï’ "

[bun]
symbol = "î¯ "

[c]
symbol = "î˜ "

[conda]
symbol = "ï„Œ "

[dart]
symbol = "î˜ "

[docker_context]
symbol = "ïŒˆ "

[elixir]
symbol = "î‰µ "

[elm]
symbol = "î˜¬ "

[golang]
symbol = "î˜§ "

[haskell]
symbol = "î· "

[java]
symbol = "îœ¸ "

[julia]
symbol = "î˜¤ "

[memory_usage]
symbol = "ï¡š "

[nim]
symbol = "ïš¤ "

[nix_shell]
symbol = "ï‹œ "

[nodejs]
symbol = "î´ "

[package]
symbol = "ï£– "

[python]
symbol = "îˆµ "

[spack]
symbol = "ğŸ…¢ "

[rust]
symbol = "î¨ "

[custom.groovy]
format = 'via [$symbol]($style) '
detect_extensions = ['groovy']
detect_files = ['.groovylintrc.json']
symbol = "ï‰› "
